package cm.aptoide.pt.downloadmanager;

public enum DownloadStatus {
  PROGRESS, IN_QUEUE, PENDING, PAUSED, ERROR, GENERIC_ERROR, NOT_ENOUGH_SPACE_ERROR, WARNING, NOT_DOWNLOADED, FILE_MISSING, INVALID_STATUS, COMPLETED, CONNECTED, RETRY, STARTED, BLOCK_COMPLETE
}
